services:
  postgres:
    image: postgres:16
    container_name: subscription-postgres
    environment:
      POSTGRES_DB: subscription
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - subscription_postgres_data:/var/lib/postgresql/data

volumes:
  subscription_postgres_data: